### PR TITLE
merge from dev - 1

### PR DESCRIPTION
**Pull request by secondincommanddeveloper**
Till now we have completed below things

1. Included a skeleton for spring boot
2. Trying Qodana as a code analyzer
3. maintaining code from vs code using git hub plugin

If we all agree, this should go to qa.

### CODE REVIEW

**Comment by secondincommanddeveloper** [comment]
Can we check if this can be merged with qa?

**Review by justAnotherProgrammmmer — APPROVED** [review]

**Comment by justAnotherProgrammmmer** [comment]
Please check unsigned commits. We need all commits to be signed. @secondincommanddeveloper

**Review by justAnotherProgrammmmer — APPROVED** [review]

**Comment by justAnotherProgrammmmer** [comment]
So far, below documents are referred while making previous commits signed

1] Setting up ssh key on github: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/about-ssh
Please follow ALL the steps

2] Making ssh agent up on your system
https://stackoverflow.com/questions/73644598/why-does-signing-commit-with-ssh-key-fail-with-invalid-format-and-failed-to

3] Signing all previous commits in one go [git filter-branch --commit-filter 'git commit-tree -S "$@";' dev]
https://gist.github.com/ArmandoKenneth/8c9ddbf5dab589a672f9427424b2b1ba

@secondincommanddeveloper : Please verify your commits and generate SSH key.

**Comment by justAnotherProgrammmmer** [comment]
Closing this request for now. Will raise another one.

**Pull request closed without merging**
